<?php

declare(strict_types=1);

namespace Phel\Composer;

use Composer\Composer;
use Composer\Package\Package;

final class DumpRuntime
{
    public function run(Composer $composer): void
    {
        /** @psalm-suppress DuplicateArrayKey */
        $packages = [
            $composer->getPackage(),
            ...$composer->getLocker()->getLockedRepository()->getPackages(),
        ];

        /** @var list<Package> $packages */
        $loadedConfig = $this->loadConfig($packages);

        /** @var string $vendorDir */
        $vendorDir = $composer->getConfig()->get('vendor-dir');
        $template = $this->createRuntimeScript($loadedConfig);
        file_put_contents($vendorDir . '/PhelRuntime.php', $template);
    }

    /**
     * @param list<Package> $packages
     *
     * @return array<string, list<string>>
     */
    private function loadConfig(array $packages): array
    {
        /** @var array<string, list<string>> $result */
        $result = [];

        foreach ($packages as $i => $package) {
            $this->loadConfigPackage($result, $i, $package);
        }

        return $result;
    }

    /**
     * @param array<string, list<string>> $result
     */
    private function loadConfigPackage(array &$result, int $i, Package $package): void
    {
        $extra = $package->getExtra();

        if (!isset($extra['phel'])) {
            return;
        }

        // First package is the current project (no dependency)
        $isRootPackage = ($i === 0);
        $pathPrefix = $isRootPackage ? '/..' : '/' . $package->getName();
        $loaderNames = $isRootPackage ? ['loader', 'loader-dev'] : ['loader'];

        /** @var array<string,array<string, string|list<string>>> $phelConfig */
        $phelConfig = $extra['phel'];

        foreach ($loaderNames as $loaderName) {
            if (!isset($phelConfig[$loaderName])) {
                continue;
            }
            $this->loadConfigNames($result, $phelConfig[$loaderName], $pathPrefix);
        }
    }

    /**
     * @param array<string, list<string>> $result
     * @param array<string, string|list<string>> $packageLoadConfig
     */
    private function loadConfigNames(array &$result, array $packageLoadConfig, string $pathPrefix): void
    {
        foreach ($packageLoadConfig as $ns => $pathList) {
            if (!isset($result[$ns])) {
                $result[$ns] = [];
            }

            if (is_string($pathList)) {
                $pathList = [$pathList];
            }

            foreach ($pathList as $path) {
                $result[$ns][] = $pathPrefix . '/' . $path;
            }
        }
    }

    /**
     * @param array<string, array<string>> $loadConfig
     */
    private function createRuntimeScript(array $loadConfig): string
    {
        $template = <<<'EOF'
<?php

// @generated by Phel
use Phel\Runtime\RuntimeSingleton;

require __DIR__ .'/autoload.php';

$rt = RuntimeSingleton::initialize();

EOF;

        foreach ($loadConfig as $ns => $paths) {
            $encodedNs = addslashes($ns);
            $pathString = implode("', __DIR__ . '", array_map('addslashes', $paths));
            $template .= "\$rt->addPath(\"$encodedNs\", [__DIR__ . '$pathString']);\n";
        }

        $template .= "\$rt->loadNs(\"phel\\\\core\");\n";
        $template .= "return \$rt;\n";

        return $template;
    }
}
